### ISSUE TITLE
ATGC content percentages don't make sense

### ISSUE THREAD

**Issue by hdashnow** [COMBINE-Australia/RNAseq-R#14]
`> actg <- atgcContent(filename="SRR1552450.fastq.gz")
actg`

```
     A      T G      C      N
[1,] 0 0.0083 0 0.0167 1.1167
```

These percentages don't add up to 100 or 1. Bug in atgcContent? Something weird in the data?

**Comment by bphipson** [comment]
I don’t actually know what’s going on with that function. I would be tempted to remove that from the material.

**Comment by hdashnow** [comment]
Okay, thanks @bphipson. I'll remove it.
